/*
 * This source file was generated by the Gradle 'init' task
 */
package com.supasulley.speazy;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;

public class App {
	
	/** Amount of time an audio recording will overlap with the previous one */
	private static final int OVERLAP_TIME = 500;
	
	/** Record duration, in milliseconds */
	private static final int RECORD_TIME = 2000;
	
	private AudioRecorder writer;
	
	public App() throws IOException
	{
		// Transfer zipped model to temp directory
		Path tempZip = Files.createTempFile("model", ".en.bin");
		tempZip.toFile().deleteOnExit();
		Files.copy(App.class.getClassLoader().getResourceAsStream("ggml-tiny.en.bin"), tempZip, StandardCopyOption.REPLACE_EXISTING);
		System.out.println("Copying GGML model to " + tempZip);
		
		Transcriber transcriber = new Transcriber(tempZip);
		
		writer = new AudioRecorder(transcriber, RECORD_TIME, OVERLAP_TIME);
		writer.run();
	}
	
	public static void main(String[] args) throws Exception
	{
		new App();
	}
}
