/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_supasulley_macrophone_Macrophone */

#ifndef _Included_com_supasulley_macrophone_Macrophone
#define _Included_com_supasulley_macrophone_Macrophone
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_supasulley_macrophone_Macrophone
 * Method:    getMicrophonePermission
 * Signature: ()Lcom/supasulley/macrophone/AVAuthorizationStatus;
 */
JNIEXPORT jobject JNICALL Java_com_supasulley_macrophone_Macrophone_getMicrophonePermission
  (JNIEnv *, jclass);

/*
 * Class:     com_supasulley_macrophone_Macrophone
 * Method:    openMicrophoneSettings
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_supasulley_macrophone_Macrophone_openMicrophoneSettings
  (JNIEnv *, jclass);

/*
 * Class:     com_supasulley_macrophone_Macrophone
 * Method:    requestMicrophoneAccess
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_supasulley_macrophone_Macrophone_requestMicrophoneAccess
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
